name: ff-mission-dashboard-env
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets>=7.6.3
  - jupyterlab>=3.0.16
  - loguru>=0.5.3
  - pandas>=1.3.0
  - pip>=21.3
  - plotly>=5.13.1
  - pre-commit>=2.15.0
  - pytest>=6.2.4
  - pytest-cov>=5.0.0
  - python>=3.9.16
  - pytimeparse>=1.1.8
  - pyyaml>=6.0
  - versioneer>=0.21
  - sphinx>=6.1.3
  - sphinx-autoapi>=2.0.1
  - sphinx_rtd_theme>=1.2.0
  - m2r2>=0.3.1
  - shapely>=1.8.2
  - geojson
  - geopandas
  - scipy>=1.10.0
  - mercury
  - streamlit
  - streamlit-folium
  - setuptools=65
  - orekit=11.0.2
  - pip:
      - git+ssh://git@github.com/pixxelhq/mda-core.git@Feature/tessellation_updates
